version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
      APP_ENV: dev
  db:
    image: mariadb:10.6.16
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mati
      MYSQL_USER: mati
      MYSQL_PASSWORD: mati
    ports:
      - "3306:3306"
